### ISSUE TITLE
Mapping of mapping now breaks highlighting

### ISSUE THREAD

**Issue by eladiosch** [davidhq/SublimeEthereum#39]
Hi.

I think the new version broke this. 

![image](https://user-images.githubusercontent.com/3090613/53872763-316dca80-3fff-11e9-9fc8-b6712aabdca7.png)

As you can see, when you introduce a mapping of a mapping it breaks all the highlighting after that line.

**Comment by davidhq** [comment]
thank you, indeed.. I rolled back the other change until better solution, soon

**Comment by davidhq** [comment]
hi

<img width="512" alt="screen shot 2019-03-06 at 13 25 48" src="https://user-images.githubusercontent.com/3899/53881242-6e43bc80-4013-11e9-9ea5-53c2d2815502.png">

fixed... with added proper nested mappings implementation so that "internal" is colored now too...

issue https://github.com/davidhq/SublimeEthereum/issues/36 should be fixed at the same time

if anything is still broken, please report asap and thank you very much

**Comment by eMarchenko** [comment]
didn't see any inconsistencies (on a small code base).
maybe it's worth checking on [Solidity tests](https://github.com/ethereum/solidity/tree/develop/test/libsolidity/syntaxTests).
