### ISSUE TITLE
Modifier in constructor doesn't work and breaks other highlightings

### ISSUE THREAD

**Issue by miguel164** [davidhq/SublimeEthereum#61]
Hi, a modifier in the constructor doesn't get highlighted as in general functions. Eg: `constructor() initializer {}`

It also breaks the highlighting of `fallback()` and `receive()` special functions if they are declared after the constructor.

Thanks.

**Comment by davidhq** [comment]
hi, tnx for report.. but strange because this should be implemented, can you please paste a full example?

here is something that I checked out but it seems ok...
<img width="825" alt="Screenshot 2022-03-21 at 16 49 41" src="https://user-images.githubusercontent.com/3899/159299233-80103304-7d05-4d99-a0d3-194cef258327.png">

maybe there is some other reason, so please send an example where it breaks for you

**Comment by miguel164** [comment]
Hi, it seems to happen only happens when the constructor has custom modifiers. Eg:

```
contract Foo
{
    modifier myModifier() {
        _;
    }

    receive() external payable {}

    fallback() external payable {}

    function bar() external myModifier {}
}
```

![Screenshots](https://user-images.githubusercontent.com/15159199/159301541-df94cec1-d646-4d5c-aa6d-f143801e8d14.png)

Without the custom modifier in the constructor declaration, special functions are correctly highlighted:

![Screenshots](https://user-images.githubusercontent.com/15159199/159302827-aae74e91-0afe-4e0f-8125-09d041514a80.png)

Regards.

**Comment by davidhq** [comment]
Tnx! [fixed](https://github.com/davidhq/SublimeEthereum/commit/ce379df36bc2795040744ccd9e000e64e9c68358).

will update when SubimeEthereum package updates v1.3.5

if something is not as it should be tomorrow, please reopen this and thank you for report again

**Comment by miguel164** [comment]
Thanks, its working now :)
